resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: dockerfile
    type: git
    source:
      uri: {{git_repo_url}}
      branch: master
      paths: [Dockerfile]
      private_key: {{git_private_key}}
      username: {{github_user}}


  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack_webook}}

  - name: docker_image
    type: docker-image
    source:
      repository: {{container_fullname}}
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_password}}
      cache: true

  - name: github_release
    type: github-release
    source:
      user: {{github_user}}
      repository: {{git_repo}}
      access_token: {{github_token}}

jobs:
  - name: docker-ansible-release
    serial: true
    plan:
      - get: dockerfile
        trigger: true
      - put: docker_image
        params:
          build: dockerfile
          tag: '{{version}}'
          tag_as_latest: true
      - put: github_release
        params:
          name: {{version}}
          tag: {{version}}
      - put: slack-alert
        params:
          channel: '#ci'
          text: |
            {{container_name}} has a new build. Check it out at:
            http://concourse-ci.correia.io/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME